apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: canary-demo
      version: v2
  template:
    metadata:
      labels:
        app: canary-demo
        version: v2
    spec:
      containers:
      - name: nginx
        image: dariocastillo11/canary-demo:v2.8
        env:
        - name: VERSION
          value: "HOLA. esta es la version v2"  # Cambia este valor
        ports:
        - containerPort: 80